"""Reporter Agent: writes the final ML analysis report.

Renders reports/template.html via Jinja2 into a standalone HTML file. The
LLM (ReportContent) supplies ONLY narrative prose - an executive summary and
an approach description. Every number in the report (dataset stats, quality
findings, the model comparison table, validation strategy, charts) comes
directly from the deterministic pipeline objects passed in here and is
rendered by the template itself, never generated by the LLM. Model-selection
reasoning/business interpretation/limitations come from the
already-validated RecommendationOutput (agents/recommender.py) - see that
module for how its cited_metrics are checked against the real evaluation
results.

The LLM prompt built here never includes the raw `metrics` dict (it embeds
the full model_comparison - see tools/model_runner.py) - it relies on the
already-small, already-verified `recommendation`, falling back to
tools.evaluation.to_llm_summary() only when no recommendation exists. The
template render below is unaffected: it always receives the full, untrimmed
`metrics`/`model_comparison`/`recommendation` objects for the actual HTML.
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Optional

from jinja2 import Environment, FileSystemLoader

from agents.llm_client import call_llm_json
from agents.schemas import (
    DataQualityReport,
    DatasetProfile,
    EvaluatorDecision,
    ExperimentPlan,
    ProblemDefinition,
    RecommendationOutput,
    ReportContent,
)
from tools.evaluation import ModelComparison, to_llm_summary
from tools.logging_config import get_logger

logger = get_logger(__name__)

SYSTEM_PROMPT = """You are the Reporter Agent in an automated ML pipeline.
You write ONLY two short pieces of narrative prose for an ML analysis
report - everything else (dataset statistics, data quality findings, the
model comparison table, charts, the recommendation and its metrics) is
rendered separately from deterministic pipeline results, not by you.

1. executive_summary: 3-5 sentences a non-technical stakeholder can read in
   30 seconds - what problem was solved, what was recommended, and how
   confident the pipeline is. Use only figures given to you below; if you
   cite a number, it must be one you were given, verbatim.
2. approach_narrative: a short plain-language description of the
   preprocessing/feature-engineering/validation approach actually taken
   (given to you as cleaning_log/feature_log/split_log/validation strategy).

Never invent a metric, model name, or result that isn't in the data you
were given. Never reference individual data rows - only aggregated findings.
"""

TEMPLATE_DIR = Path(__file__).resolve().parent.parent / "reports"
OUTPUT_DIR = TEMPLATE_DIR / "generated"


def generate_report(
    business_description: str,
    plan: ExperimentPlan,
    metrics: dict,
    decision: EvaluatorDecision,
    dataset_profile: Optional[DatasetProfile] = None,
    data_quality_report: Optional[DataQualityReport] = None,
    problem_definition: Optional[ProblemDefinition] = None,
    recommendation: Optional[RecommendationOutput] = None,
    cleaning_log: Optional[dict] = None,
    feature_log: Optional[dict] = None,
    feature_selection_log: Optional[dict] = None,
    split_log: Optional[dict] = None,
    charts: Optional[dict] = None,
    output_path: Optional[str] = None,
) -> str:
    prompt_parts = [
        f"Business description:\n{business_description}",
        f"Pipeline plan (JSON):\n{plan.model_dump_json(indent=2)}",
        f"Evaluator decision (JSON):\n{decision.model_dump_json(indent=2)}",
    ]
    if dataset_profile is not None:
        prompt_parts.append(f"Dataset profile (JSON):\n{dataset_profile.model_dump_json(indent=2)}")
    if data_quality_report is not None:
        prompt_parts.append(f"Data quality report (JSON):\n{data_quality_report.model_dump_json(indent=2)}")
    if problem_definition is not None:
        prompt_parts.append(f"Problem definition (JSON):\n{problem_definition.model_dump_json(indent=2)}")
    if recommendation is not None:
        # Already small and verified against the full model_comparison by
        # agents/recommender.py's validate_recommendation - sufficient on its
        # own for executive_summary/approach_narrative, so the full `metrics`
        # dict (which duplicates model_comparison) is never sent here.
        prompt_parts.append(f"Recommendation (JSON):\n{recommendation.model_dump_json(indent=2)}")
    else:
        # Edge case: the recommender step didn't run (e.g. no candidate
        # produced a usable result). Fall back to a trimmed model_comparison
        # summary instead of the raw `metrics` dict - never crash report
        # generation over a missing/malformed comparison.
        try:
            raw_comparison = metrics.get("model_comparison")
            if raw_comparison:
                comparison = ModelComparison.model_validate(raw_comparison)
                prompt_parts.append(
                    f"Model comparison summary (JSON):\n{json.dumps(to_llm_summary(comparison), indent=2)}"
                )
        except Exception as exc:  # noqa: BLE001 - prompt-only fallback, never fails report generation
            logger.warning("reporter_model_comparison_summary_failed", extra={"error": str(exc)})
    if cleaning_log is not None:
        prompt_parts.append(f"Cleaning log (JSON):\n{json.dumps(cleaning_log, indent=2)}")
    if feature_log is not None:
        prompt_parts.append(f"Feature engineering log (JSON):\n{json.dumps(feature_log, indent=2)}")
    if feature_selection_log is not None:
        # Absent for hierarchical scope (no selection applies there) - a
        # missing/None value here is a valid, expected state, not an error.
        prompt_parts.append(f"Feature selection log (JSON):\n{json.dumps(feature_selection_log, indent=2)}")
    if split_log is not None:
        prompt_parts.append(f"Split log (JSON):\n{json.dumps(split_log, indent=2)}")

    user_prompt = "\n\n".join(prompt_parts)
    content = call_llm_json(SYSTEM_PROMPT, user_prompt, ReportContent, caller_name="agents.reporter")

    env = Environment(loader=FileSystemLoader(str(TEMPLATE_DIR)))
    template = env.get_template("template.html")
    html = template.render(
        generated_at=datetime.now().isoformat(timespec="seconds"),
        business_description=business_description,
        plan=plan,
        metrics=metrics,
        model_comparison=metrics.get("model_comparison"),
        decision=decision,
        content=content,
        dataset_profile=dataset_profile,
        data_quality_report=data_quality_report,
        problem_definition=problem_definition,
        recommendation=recommendation,
        cleaning_log=cleaning_log,
        feature_log=feature_log,
        feature_selection_log=feature_selection_log,
        split_log=split_log,
        charts=charts or {},
    )

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = Path(output_path) if output_path else OUTPUT_DIR / f"report_{datetime.now():%Y%m%d_%H%M%S}.html"
    out_path.write_text(html, encoding="utf-8")
    return str(out_path)
